before_install:
  - which bundle || gem install bundler
  # - sudo apt-get -qq update
  # - sudo apt-get install -y libxml2-dev

language: ruby
rvm:
 #- 2.2
 - 2.4.0
 # - jruby
 # - rbx-2
# uncomment and edit the following line if your project needs to run something other than `rake`:
script: bundle exec rspec spec

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres